### ISSUE TITLE
How to monitor each PWM signal?

### ISSUE THREAD

**Issue by Peter286** [davidbuzz/BuzzsArduinoCode#3]
Hi,

I have uploaded your code, and your code is working well on my Arduino Nano. I am using a 8 channel R2008SB Futaba radio receiver and a Pixhawk as the flight controller. I connected the 8 PWM signals of the radio receiver to the digital pins D0 to D7 of the Arduino, that is, channel 1 to D0, channel 2 to D1, ... , channel 7 to D6, channel 8 to D7. The PPM signal from the digital pin D10 of the Arduino to the RC signal pin of the Pixhawk. The Pixhawk is able to arm, and the motors are able to spin.

I am working on collision avoidance system for my drone. There is an infrared-red sensor in front of the drone to sense whether there is any obstacle. I am looking into how to modify the pitch channel so that if there is an obstacle in front of the drone, the drone will pitch up and move backwards. However, I do not know where to find each PWM channel data in your code, please kindly tell us where to obtain each channel data.

Also, I am interested to learn how to assign each radio receiver channel to each digital pin of the Arduino.

I hope you are able to help me. Thanks for your time and effort.

**Comment by davidbuzz** [comment]
did you have a look inside the PPM_Encoder.h ?       you should particularly look at the array called 'volatile uint16_t ppm'   as that's where the pulse width/s are saved.     the code that does the "work" of copying from the PWMs to the PPM is inside the Interrup handler called "ISR( SERVO_INT_VECTOR )".

**Comment by Peter286** [comment]
Dear David,

I tried modifying the void loop of your buzz_8pwm_to_ppm328.ino
<https://github.com/davidbuzz/BuzzsArduinoCode/blob/master/buzz_8pwm_to_ppm328/buzz_8pwm_to_ppm328.ino>
code and I opened the serial monitor at 115200 baud on the Arduino
application. The channel 1 responded to the roll command, however, channel
2 to channel 8 did not respond. My radio transmitter is Mode 1. I do not
know how to obtain the pulse width information for each channel. Did I code
correctly? Please help me. Thanks for your time.

Here is the modified void loop.

void loop()
{

 //
------------------------------------------------------------------------------------------------------------------------------------------------------------
 // AUXILIARY TASKS
 //
------------------------------------------------------------------------------------------------------------------------------------------------------------
 PWM_LOOP: // SERVO_PWM_MODE
 while( 1 )
 {
                Serial.print ("Ch 1: ");   //roll
                Serial.print (ppm[1]);
                Serial.print ("     ");
                Serial.print ("Ch 2: ");   //pitch
                Serial.print (ppm[2]);
                Serial.print ("     ");
                Serial.print ("Ch 3: ");  //throttle
                Serial.print (ppm[3]);
                Serial.print ("     ");
                Serial.print ("Ch 4: ");   //yaw
                Serial.print (ppm[4]);
                Serial.print ("     ");
                Serial.print ("Ch 5: ");
                Serial.print (ppm[5]);
                Serial.print ("     ");
                Serial.print ("Ch 6: ");
                Serial.print (ppm[6]);
                Serial.print ("     ");
                Serial.print ("Ch 7: ");
                Serial.print (ppm[7]);
                Serial.print ("     ");
                Serial.print ("Ch 8: ");
                Serial.println (ppm[8]);

  _delay_us (950); // Slow down while loop

 } // PWM Loop end



} // main lopo function end
